version: '3.7'
services:
  strapi:
    image: strapi/strapi:3.5.3
    container_name: strapi
    env_file: .env
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: strapi_db
      DATABASE_PORT: 3306
      DATABASE_NAME: $DATABASE_NAME
      DATABASE_USERNAME: $DATABASE_USERNAME
      DATABASE_PASSWORD: $DATABASE_PASSWORD
    ports:
      - '${STRAPI_PORT:-1337}:1337'
    volumes:
      - ./:/srv/app
    depends_on:
      - strapi_db
    networks:
      - strapi_db_net
  strapi_db:
    container_name: strapi_db
    hostname: strapi_db
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: strapiroot
      MYSQL_PASSWORD: $DATABASE_PASSWORD
      MYSQL_USER: $DATABASE_USERNAME
      MYSQL_DATABASE: $DATABASE_NAME
    networks:
      - strapi_db_net
    volumes:
      - strapi_db_data:/var/lib/mysql
networks:
  strapi_db_net:
volumes:
  strapi_db_data:
    driver: local
