name: deploy
on:
  push:
    branches:
      - master
      - chore/add-cd

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: ${{ secrets.SCALEWAY_REGISTRY }}
          username: ${{ secrets.SCALEWAY_REGISTRY_LOGIN }}
          password: ${{ secrets.SCALEWAY_SECRET_KEY }}

      - name: Build and push back
        id: docker_build_back
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.SCALEWAY_REGISTRY }}/${{ secrets.SCALEWAY_APP_IMAGE_PREFIX }}_production:latest
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=registry,ref=${{ secrets.SCALEWAY_REGISTRY }}/${{ secrets.SCALEWAY_APP_IMAGE_PREFIX }}_production:latest
          cache-to: type=inline
  
  deploy:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Clone devops repo
        run: git clone https://github.com/IIM-Green-Team/devops

      - name: create ssh folder
        run: |
          mkdir -p ./devops/automation/ansible/keys/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ./devops/automation/ansible/keys/.ssh/id_rsa
          chmod 600 ./devops/automation/ansible/keys/.ssh/id_rsa

      - name: create vault_pass file
        run: |
          echo "${{ secrets.VAULT_PASS }}" > ./devops/automation/ansible/.vault_pass

      - name: run ansible playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          directory: ./devops/automation/ansible
          playbook: production.yml
          vault_password: ${{ secrets.VAULT_PASS }}
          options: |
            --inventory ./inventory/hosts
            --key ./keys/.ssh/id_rsa
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
    
